type: object
properties:
  name:
    type: string
    description: Имя документа
    example: "photo.jpg"
  file:
    type: boolean
    description: Является ли документ файлом
    example: true
  public:
    type: boolean
    description: Является ли документ публичным
    example: false
  token:
    type: string
    description: Токен авторизации
    example: "sfuqwejqjoiu93e29"
  mime:
    type: string
    description: MIME тип документа
    example: "image/jpg"
  grant:
    type: array
    items:
      type: string
    description: Список логинов пользователей, которым предоставлен доступ
    example: ["login1", "login2"]
required:
  - name
  - file
  - public
  - token
  - mime
