version: '3'

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.24'
  OGEN_VERSION: 'v1.12.0'
  YQ_VERSION: 'v4.45.2'

  # Директория для бинарников
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  # Бинарник ogen
  OGEN: '{{.BIN_DIR}}/ogen'
  # Бинарник yq
  YQ: '{{.BIN_DIR}}/yq'
  # Бинарник redocly
  NODE_MODULES_DIR: '{{.ROOT_DIR}}/node_modules/.bin'
  # Бинарник redocly
  REDOCLY: '{{.NODE_MODULES_DIR}}/redocly'

  OPEN_API_DOCS_V1_BASE: '{{.ROOT_DIR}}/pkg/openapi/fileserver/v1/fileserver.openapi.yaml'
  OPEN_API_DOCS_V1_BUNDLE: '{{.ROOT_DIR}}/pkg/openapi/bundles/docs.openapi.bundle.yaml'

  OPEN_API_FILES: '{{.ROOT_DIR}}/pkg/openapi/bundles'

tasks:
  format:
    desc: "Форматирует код"
    summary: |
      Эта задача форматирует код проекта.

    cmds:
      - go fmt ./...

  lint:
    desc: "Проверяет код на ошибки"
    summary: |
      Эта задача проверяет код на ошибки.

    cmds:
      - go vet ./...
      - go lint ./...

  redocly-cli:install:
    desc: Установить локально Redocly CLI
    cmds:
      - |
        [ -f {{.REDOCLY}} ] || {
          npm ci
        }

  redocly-cli:docs-v1-bundle:
    desc: Собрать OpenAPI в один файл через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - '{{.REDOCLY}} bundle {{.OPEN_API_DOCS_V1_BASE}} -o {{.OPEN_API_DOCS_V1_BUNDLE}}'

  redocly-cli:bundle:
    desc: Собрать все схемы OpenAPI в общие файлы через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - task: redocly-cli:docs-v1-bundle

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          mkdir -p {{.BIN_DIR}}
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  yq:install:
    desc: "Устанавливает yq в bin/ при необходимости"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Installing yq...'
          GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }

  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ ogen:install, yq:install ]
    cmds:
      - task: redocly-cli:bundle
      - |
        find {{.OPEN_API_FILES}} -name '*.yaml' -o -name '*.yml' | while read -r file; do
          if [ -f "$file" ] && grep -q 'x-ogen:' "$file"; then
            echo "🚀 Generating from: $file"
            target=$({{.YQ}} e '."x-ogen".target' "$file")
            package=$({{.YQ}} e '."x-ogen".package' "$file")
            echo "📁 Target: $target"
            echo "📦 Package: $package"
            {{.OGEN}} \
              --target "$target" \
              --package "$package" \
              --clean \
              "$file" || exit 1
          fi
        done
