openapi: 3.0.3
info:
  title: File Server Service API
  version: 1.0.0
  description: API для сервиса файлового хранилища с аутентификацией
x-ogen:
  target: ./pkg/generated/api/fileserver/v1
  package: fileserver_v1
  clean: true

servers:
  - url: http://localhost:8080
    description: Development server
tags:
  - name: auth
    description: Authentication operations
  - name: docs
    description: Document management operations
paths:
  /api/auth/register:
    $ref: "./paths/auth_register.yaml"
  /api/auth/login:
    $ref: "./paths/auth_login.yaml"
  /api/auth/logout:
    $ref: "./paths/auth_logout.yaml"
  /api/docs:
    $ref: "./paths/docs.yaml"
  /api/docs/{doc_id}:
    $ref: "./paths/docs_by_id.yaml"
  /api/docs/{doc_id}/download:
    $ref: "./paths/docs_download.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      $ref: "./components/user_dto.yaml"
    Document:
      $ref: "./components/document_dto.yaml"
    Error:
      $ref: "./components/errors/generic_error.yaml"
security:
  - bearerAuth: []
